### PR TITLE
trailing whitespace fixes

### LINKED ISSUE #2: Trailing whitespace in compound names
See https://github.com/IDR/idr0094-ellinger-sarscov2/issues/14

Several of the compound names in that list have a trailing whitespace in idr0064.

Repeat of that query on idr-next, which has fixes for idr0094 and idr0088 applied, gives...

```
[wmoore@prod111-omeroreadwrite ~]$ /opt/omero/server/OMERO.server/bin/omero hql "select mv.value from MapAnnotation m join m.mapValue as mv where mv.value like '% ' and m.ns='openmicroscopy.org/mapr/compound'"

Created session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
 #  | Col1                                    
----+-----------------------------------------
 0  | Dovitinib Dilactic Acid                 
 1  | AG-1024                                 
 2  | CX-6258 HCl                             
 3  | Tyrphostin 9                            
 4  | EHop-016                                
 5  | PIK-75                                  
 6  | BMS-582949                              
 7  | Olmutinib                               
 8  | VX-11e                                  
 9  | PF-299804                               
 10 | 4,2,4'-Tribenzyloxy-6'-hydroxychalcone  
(11 rows)
```

### PR DESCRIPTION
**Pull request by will-moore**
Fixes #2.

Fix compound trailing whitespaces in screenA/idr0064-screenA-annotations.csv

### CODE REVIEW

**Comment by will-moore** [comment]
On idr-next, remove 'compound' KVP and update (after checkout out this branch)...

```
(venv3) [wmoore@prod111-omeroreadwrite idr0064-goglia-erkdynamics]$ omero metadata populate --context deletemap --report --wait 300 --batch 100 --localcfg '{"ns":["openmicroscopy.org/mapr/compound"], "typesToIgnore":["Annotation"]}' --cfg screenA/idr0064-screenA-bulkmap-config.yml Screen:2351

omero metadata deletebulkanns Screen:2351

omero metadata populate --report --batch 1000 --file screenA/idr0064-screenA-annotation.csv Screen:2351

omero metadata populate --context bulkmap --batch 100 --cfg screenA/idr0064-screenA-bulkmap-config.yml --localcfg '{"ns":["openmicroscopy.org/mapr/compound"]}' Screen:2351
```

**Comment by will-moore** [comment]
After update above... and fixes from https://github.com/IDR/idr0094-ellinger-sarscov2/pull/15...

```
(venv3) [wmoore@prod111-omeroreadwrite idr0064-goglia-erkdynamics]$ omero hql "select mv.value, m.id from MapAnnotation m join m.mapValue as mv where mv.value like '% ' and m.ns='openmicroscopy.org/mapr/compound'"
Using session for demo@localhost:4064. Idle timeout: 10 min. Current group: Public
 # | Col1                                    | Col2     
---+-----------------------------------------+----------
 0 | 4,2,4'-Tribenzyloxy-6'-hydroxychalcone  | 27342509 
 1 | PF-299804                               | 35619132 
(2 rows)
```

`4,2,4'-Tribenzyloxy-6'-hydroxychalcone` is from idr0088
`PF-299804` is from idr0133 (expA)

cc @dominikl @francesw

**Comment by will-moore** [comment]
NB: error was fixed by [95e1298](https://github.com/IDR/idr0064-goglia-erkdynamics/pull/3/commits/95e12987a463469b7055526313d88546eb0b9cda)

```
....
  unwrap(ma.getId()), str(r)))
Exception: Duplicate MapAnnotation primary key: id:35666098 ns:openmicroscopy.org/mapr/compound primary:('openmicroscopy.org/mapr/compound', frozenset({('Compound Name', 'CK-869')})) keyvalues:[('Compound Name', 'CK-869'), ('Compound Name URL', 'https://pubchem.ncbi.nlm.nih.gov/compound/3574452')] parents:set() id:35666098
```

**Review by sbesson — APPROVED** [review]
https://github.com/IDR/idr0064-goglia-erkdynamics/pull/3/files?diff=unified&w=1 makes sense to me

**Comment by will-moore** [comment]
I think these changes are all released now - good to merge this PR?

**Pull request merged**
